mex -R2018a -v CC='/usr/local/Cellar/llvm/8.0.0/bin/clang' ...
    FspCvodeMex.c '-I/usr/local/include' '-I./src' ...
    '-L./' '-L/usr/local/lib' -lFspCvode -lsundials_cvodes -lsundials_nvecserial

mex -R2018a -v CC='/usr/local/Cellar/llvm/8.0.0/bin/clang' ...
    FspSensCvodeMex.c '-I/usr/local/include' '-I./src' ...
    '-L./' '-L/usr/local/lib' -lFspCVodeForwardSens -lsundials_cvodes -lsundials_nvecserial

cd ..